key_mapping = {
    "V": {"name": "VS_Batteriespannung", "unit": "V", "icon": "mdi:flash", "scale": 0.001, "round":2}, 
    "I": {"name": "VS_Batteriestrom", "unit": "A", "icon": "mdi:current-dc", "scale": 0.001, "round":2 },
    "P": {"name": "VS_Leistung", "unit": "W", "icon": "mdi:flash" },
    "CE": {"name": "VS_Verbrauchte Ah", "unit": "Ah", "icon": "mdi:battery-minus", "scale": 0.001, "round":1 },
    "FW": {"name": "VS_Firmware-Version", "unit": None, "icon": "mdi:chip"}, 
    "SER": {"name": "VS_Seriennummer", "unit": None, "icon": "mdi:barcode"}, 
    "SOC": {"name": "VS_Ladezustand", "unit": "%", "icon": "mdi:battery", "scale": 0.1 }, 
    "TTG": {"name": "VS_Verbleibende Zeit", "unit": "h", "icon": "mdi:timer-outline", "scale": 0.016666666666666666, "round":2}, 
    "Alarm": {"name": "VS_Alarmstatus", "unit": None, "icon": "mdi:alert" }, 
    "H1": {"name": "VS_Tiefste Entladung", "unit": "Ah", "icon": "mdi:history", "scale": 0.001,"round":1 }, 
    "H2": {"name": "VS_Letzte Entladung", "unit": "Ah", "icon": "mdi:history", "scale": 0.001,"round":1}, 
    "H3": {"name": "VS_Durchschnittliche Entladung", "unit": "Ah", "icon": "mdi:battery-arrow-down", "scale": 0.001,"round":1}, 
    "H7": {"name": "VS_Min. Batteriespannung", "unit": "V", "icon": "mdi:flash-outline", "scale": 0.001, "round":2 }, 
    "H8": {"name": "VS_Zeit seit letztem vollständigem Aufladen", "unit": "h", "icon": "mdi:timer-sand", "scale": 0.016666666666666666, "round":2}, 
    "H15": {"name": "VS_Min. Spannung Starter", "unit": "V", "icon": "mdi:battery-arrow-down-outline", "scale": 0.001, "round":2}, 
    "H16": {"name": "VS_Max. Spannung Starter", "unit": "V", "icon": "mdi:battery-arrow-up-outline", "scale": 0.001, "round":2}, 
    "H17": {"name": "VS_Entladene Energie", "unit": "kWh", "icon": "mdi:battery-arrow-down", "scale": 0.01, "round":1}, 
    "H18": {"name": "VS_Geladene Energie", "unit": "kWh", "icon": "mdi:flash", "scale": 0.01, "round":1},
    "AR": {"name": "VS_Alarmursache", "unit": None, "icon": "mdi:alert-circle"},
    "PID": {"name": "VS_Produkt-ID", "unit": None, "icon": "mdi:identifier"},
    "BMV": {"name": "VS_Batterie Monitor", "unit": None, "icon": "mdi:battery"},
    "H4": {"name": "VS_Ladezyklen insgesamt", "unit": None, "icon": "mdi:refresh"},
    "H5": {"name": "VS_Ladezyklen", "unit": None, "icon": "mdi:battery-charging"},
    "H6": {"name": "VS_Max. Batteriespannung", "unit": "V", "icon": "mdi:flash-outline", "scale": 0.001, "round":2}, 
    "H9": {"name": "VS_Automatische Synchronisationen", "unit": None, "icon": "mdi:sync"},
    "H10": {"name": "VS_Unterspannung-Alarme", "unit": None, "icon": "mdi:alert-octagram"},
    "H11": {"name": "VS_Überspannung-Alarme", "unit": None, "icon": "mdi:alert-octagram"},
    "H12": {"name": "VS_Unterspannung-Starter-Alarme", "unit": None, "icon": "mdi:alert-circle-outline"},
}