key_mapping = {
    "PID": {"name": "Produkt-ID", "unit": None, "icon": "mdi:identifier"},   
    "FW": {"name": "Firmware-Version", "unit": None, "icon": "mdi:chip","scale": 0.01, }, 
    "SER#": {"name": "Seriennummer", "unit": None, "icon": "mdi:barcode"}, 
    "V": {"name": "Batteriespannung", "unit": "V", "icon": "mdi:flash", "scale": 0.001, "round": 2}, 
    "I": {"name": "Batteriestrom", "unit": "A", "icon": "mdi:current-dc", "scale": 0.001 }, 
    "VPV": {"name": "PV-Spannung", "unit": "V", "icon": "mdi:solar-power", "scale": 0.001 }, 
    "PPV": {"name": "PV-Leistung", "unit": "W", "icon": "mdi:solar-power", "scale": 0.001 }, 
    "CS": {"name": "Ladestatus", "unit": None, "icon": "mdi:power-settings", "scale": 0.001 }, 
    "MPPT": {"name": "MPPT-Modus", "unit": None, "icon": "mdi:solar-power" }, 
    "OR": {"name": "Betriebsstatus", "unit": None, "icon": "mdi:information"}, 
    "ERR": {"name": "Fehlercode", "unit": None, "icon": "mdi:alert"}, 
    "LOAD": {"name": "Lastausgang", "unit": None, "icon": "mdi:power"}, 
    "IL": {"name": "Laststrom", "unit": "A", "icon": "mdi:current-dc", "scale": 0.001 }, 
    "H19": {"name": "Gesamtertrag", "unit": "kWh", "icon": "mdi:calendar", "scale": 0.01, "round": 2 }, 
    "H20": {"name": "Ertrag heute", "unit": "kWh", "icon": "mdi:calendar-today", "scale": 0.001 }, 
    "H21": {"name": "Ertrag gestern", "unit": "kWh", "icon": "mdi:calendar-today", "scale": 0.001 }, 
    "H22": {"name": "Ertrag letzte 30 Tage", "unit": "kWh", "icon": "mdi:calendar-month", "scale": 0.001 }, 
    "H23": {"name": "Tagesmaximum PV-Spannung", "unit": "V", "icon": "mdi:flash", "scale": 0.001 }, 
    "HSDS": {"name": "Tageszählstand", "unit": None, "icon": "mdi:counter", "scale": 0.001 }, 
}
